wip; cleanup

diff --git a/dependency/test/bionic/entrypoint b/dependency/test/bionic/entrypoint
--- a/dependency/test/bionic/entrypoint
+++ b/dependency/test/bionic/entrypoint
@@ -1,35 +1,29 @@
 #!/usr/bin/env bash
 
 set -euo pipefail
-set -x
-
-parent_dir="$(cd "$(dirname "$0")" && pwd)"
 
 extract_tarball() {
   rm -rf httpd
-  tar -xf /tarball_path/httpd-2.4.54-bionic.tgz
+  tar -xf "/tarball_path/httpd-${version}-bionic.tgz"
 }
 
 set_ld_library_path() {
   export LD_LIBRARY_PATH="$PWD/httpd/lib:${LD_LIBRARY_PATH:-}"
-  echo "${LD_LIBRARY_PATH}"
-  ls -lah /httpd/lib
 }
 
 check_version() {
-  expected_version=$1
   actual_version="$(./httpd/bin/httpd -v | head -n1 | cut -d' ' -f3 | cut -d'/' -f2)"
-  if [[ "${actual_version}" != "${expected_version}" ]]; then
-    echo "Version ${actual_version} does not match expected version ${expected_version}"
+  if [[ "${actual_version}" != "${version}" ]]; then
+    echo "Version ${actual_version} does not match expected version ${version}"
     exit 1
   fi
 }
 
-check_server() { # bionic httpd dependency passes! jammy is failing; error msg says libc and libcrypt are required
+check_server() {
   SERVER_ROOT="$PWD/httpd" \
-    APP_ROOT="${parent_dir}/fixtures" \
+    APP_ROOT="/fixtures" \
     PORT=8080 \
-    ./httpd/bin/httpd -f "${parent_dir}/fixtures/httpd.conf" -k start
+    ./httpd/bin/httpd -f "/fixtures/httpd.conf" -k start
 
   set +e
 
@@ -54,12 +48,34 @@ check_server() { # bionic httpd dependency passes! jammy is failing; error msg s
 }
 
 main() {
+  local version
+  version=
+
+  while test $# -gt 0; do
+    case $1 in
+      --version)
+        version=$2
+        shift
+        ;;
+      *)
+        echo >&2 "Invalid argument: $1"
+        exit 1
+        ;;
+    esac
+    shift
+  done
+
+  if [[ "${version}" == "" ]]; then
+    echo "Version is required"
+    exit 1
+  fi
+
   extract_tarball
   set_ld_library_path
-  check_version "$1"
+  check_version
   check_server
 
-  echo "All tests passed!"
+  echo "All HTTPD bionic dependency tests passed!"
 }
 
-main "$@"
+main "${@:-}"
